name: Build and Deploy to PyPI

on:
  push:
    paths:
      - .github/workflows/build_manylinux_image.yml #XXX when file is modified and merge to master

jobs:
  build_manylinux:
    name: Rebuild manylinux on arch ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64, ppc64le, s390x] #aarch64 is easyly timeout in github action, maybe need to build in local
    timeout-minutes: 1200
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        path: build_docker

    - name: Check out manylinux repo
      uses: actions/checkout@v3
      with:
        repository: pypa/manylinux
        path: manylinux
        ref: 02cacafe8f8c82b06f71b7e9c242fd7b187f2c34

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: rebuild manylinux images with shared python libraries for arch ${{ matrix.arch }}
      run: |
        cd manylinux
        git apply ../build_docker/patch/shared_python_based_02cacafe8f8c82b06f71b7e9c242fd7b187f2c34.patch
        PLATFORM=${{ matrix.arch }} POLICY=manylinux2014 COMMIT_SHA=latest ./build.sh
        docker image tag quay.io/pypa/manylinux2014_${{ matrix.arch }}:latest smartbrave/manylinux2014_${{ matrix.arch }}_shared_python:latest
     
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Push image
      run: |
        docker push smartbrave/manylinux2014_${{ matrix.arch }}_shared_python:latest 
