name: Build and Deploy to PyPI

on:
  push:
    paths:
      - .github/workflows/build_manylinux_image.yml

jobs:
  build_manylinux:
    name: Rebuild manylinux on arch ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64, ppc64le, s390x]
    steps:
    - name: Check out manylinux repo
      uses: actions/checkout@v3
      with:
        repository: pypa/manylinux
        path: manylinux
        ref: 02cacafe8f8c82b06f71b7e9c242fd7b187f2c34

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: rebuild manylinux images with shared python libraries for arch ${{ matrix.arch }}
      run: |
        cd manylinux
        sed -i 's/--disable-shared/--enable-shared/g' docker/build_scripts/build-cpython.sh
        sed -i '/RUN manylinux-entrypoint \/build_scripts\/finalize-python.sh/d' docker/Dockerfile
        sed -i 's/^[ \t]*${PREFIX}\/bin\/python/LD_LIBRARY_PATH=${PREFIX}\/lib ${PREFIX}\/bin\/python/g' docker/build_scripts/finalize.sh
        sed -i 's/^[ \t]*${PREFIX}\/bin\/pip/LD_LIBRARY_PATH=${PREFIX}\/lib ${PREFIX}\/bin\/pip/g' docker/build_scripts/finalize.sh
        sed -i 's/$(${PREFIX}\/bin\/python/$(LD_LIBRARY_PATH=${PREFIX}\/lib ${PREFIX}\/bin\/python/g' docker/build_scripts/finalize.sh
        sed -i 's/^\/opt\/python\/cp310-cp310\/bin\/python/LD_LIBRARY_PATH=\/opt\/python\/cp310-cp310\/lib \/opt\/python\/cp310-cp310\/bin\/python/g' docker/build_scripts/finalize.sh
        sed -i 's/^pip install/LD_LIBRARY_PATH=\/opt\/python\/cp310-cp310\/lib pip install/g' docker/build_scripts/finalize.sh
        sed -i 's/^${TOOLS_PATH}\/bin\/pipx/LD_LIBRARY_PATH=\/opt\/python\/cp310-cp310\/lib ${TOOLS_PATH}\/bin\/pipx/g' docker/build_scripts/finalize.sh
        sed -i 's/^[ \t]*$PYTHON/LD_LIBRARY_PATH=$(dirname $PYTHON)\/..\/lib $PYTHON/g' tests/run_tests.sh
        sed -i 's/$(${PYTHON}/$(LD_LIBRARY_PATH=$(dirname ${PYTHON})\/..\/lib ${PYTHON}/g' tests/run_tests.sh
        sed -i 's/$(${LINK_PREFIX}/$(LD_LIBRARY_PATH=$(dirname ${PYTHON})\/..\/lib ${LINK_PREFIX}/g' tests/run_tests.sh
        sed -i '/ssl-check.py/s/^/#/g' tests/run_tests.sh
        sed -i 's/^auditwheel --version/export LD_LIBRARY_PATH=\/opt\/python\/cp310-cp310\/lib\nauditwheel --version/g' tests/run_tests.sh
        sed -i '$i\ENV LD_LIBRARY_PATH=\/opt\/python\/cp38-cp38\/lib:\/opt\/python\/cp310-cp310\/lib' docker/Dockerfile
        PLATFORM=${{ matrix.arch }} POLICY=manylinux2014 COMMIT_SHA=latest ./build.sh
        docker image tag quay.io/pypa/manylinux2014_${{ matrix.arch }}:latest smartbrave/manylinux2014_${{ matrix.arch }}_shared_python:latest
     
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Push image
      run: |
        docker push smartbrave/manylinux2014_${{ matrix.arch }}_shared_python:latest 
